### ISSUE TITLE
Missing direct downloads for APKs

### ISSUE THREAD

**Issue by rausm** [qpython-android/qpython3#11]
Not everyone is happy with Google collecting & selling more & more info about our daily lives.

Please, provide good old-fashioned links for those of us who sabotage their attempts on principle.

**Comment by riverfor** [comment]
QPython3 1.2.0 BETA-2 (With Python 3.6.1) Needs android 5.0+
https://github.com/qpython-android/qpython3/releases/tag/1.2.0-BETA-2

QPython's 2.0 BETA-1 （With Python 2.7.12)
https://github.com/qpython-android/qpython/releases/tag/2.0.0-BETA-1

And you could see other direct download APKs by entering the Releases.

**Comment by rausm** [comment]
At the time I wrote it, no new release was listed on github for more than half a year (I even thought QPython was maybe dead). And i wrote it _AFTER_ discovering elsewhere that a new version was indeed released (and available on appstore / through apk downloaders), but still no direct links were mentioned either on QPython site or github.

QPython3 - Python3 for Android 1.0.1 for Android 2.3.2+ APK Download
    Version: 1.0.1 (101) for Android 2.3.2+ (Gingerbread, API 9)
    Update on: 2017-03-08

Still not listed on the releases page.

So no, ME AND NOBODY ELSE COULD NOT SEE ANYTHING (current), AND THAT WAS THE REASON I MENTIONED IT !!!
