### ISSUE TITLE
File-writing

### ISSUE THREAD

**Issue by antorix** [qpython-android/qpython3#4]
Dear devs! Do you plan to add file-writing (file.write(), pickle etc.)? Because right now, I just can't figure out how to use QPython for any kind of serious programming. I really hope you do, because QPython is great in many respects. But now I just can't use it.

**Comment by riverfor** [comment]
Can you use the absolute path like /sdcard/sample.txt in your script ?

**Comment by antorix** [comment]
Thanks for replying and closing. File-writing finally became possible in the new 1.0 version.
