### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by ramin1695** [qpython-android/qpython3#40]
I have this error in both qpython 2.7 and 3 when switching to qpython 3.6 from setting
![img_20180131_175654_690](https://user-images.githubusercontent.com/30201481/35628354-ea80e608-06b0-11e8-9a02-7a2e1d1b4b2e.jpg)

**Comment by creepersbane** [comment]
Same

**Comment by ramin1695** [comment]
solved by updating Android version to 7
