### ISSUE TITLE
Cannot Install Tensorflow on QPython3

### ISSUE THREAD

**Issue by ReKuZa** [qpython-android/qpython3#63]
![Screenshot_2020-01-31-20-37-05-595_org qpython qpy3](https://user-images.githubusercontent.com/38037669/73549879-81504e00-4469-11ea-850d-3c9cba07f23b.png)

**Comment by riverfor** [comment]
Sorry, QPython will not support tensorflow in the near future, I suggest you to consider keras  is a high-level neural networks API, written in Python and capable of running on top of TensorFlow, CNTK, or Theano and you can install keras-aipy3 from QPYPI.

We will announce it in facebook(https://www.facebook.com/qpython) when QPython supports tf in the future.
