### ISSUE TITLE
How to install pygame?

### ISSUE THREAD

**Issue by Faith-Mian** [qpython-android/qpython3#74]
No pygame in QPYPI . Failed to install pygame in PYPI . What can I do ? 
HELP ME PLEASE!

**Comment by Supriyo-455** [comment]
Try this command it should work:
python3 -m pip install -U pygame --user

**Comment by Faith-Mian** [comment]
![Uploading Screenshot_2020-09-07-14-47-37-489_org.qpython.qpy3.jpg…]()
Thank you ! Supriyo-455 !!!
