### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by atbest** [qpython-android/qpython3#8]
Is three any plan to upgrade python version from 3.2 to higher version? Python 3.2 doesn't support u"" syntax, which is required in some third-party modules. 

Thanks.

**Comment by marat1995** [comment]
+
I think, this project is dead.

**Comment by riverfor** [comment]
No, we are reactivating it now. see the progress in  http://github.com/qpython-android/qpython .

The python core will be upgrade later.

**Comment by ale5000-git** [comment]
@riverfor: I would be more secure if I can see ALL the sources online.

What is the problem of publishing them? It isn't a thing that need time, just some clicks and they are online.

**Comment by marat1995** [comment]
@ale5000-git you can find sources on your Android device.
Open /data/data/qpython3's folder/lib(root)
Enjoy!
Sorry for bad English.

**Comment by ale5000-git** [comment]
@marat1995: I haven't looked here yet but the main point of github is to host sources, documentation and support are secondary.

**Comment by Z4HD** [comment]
How to upgrade Python version in QPython?

**Comment by riverfor** [comment]
QPython3  1.2.0 BETA-2  (With Python 3.6.1) Needs android 5.0+
https://github.com/qpython-android/qpython3/releases/tag/1.2.0-BETA-2

QPython's 2.0 BETA-1 （With Python 2.7.12)
https://github.com/qpython-android/qpython/releases/tag/2.0.0-BETA-1

**Comment by Magissia** [comment]
Please support Android 4.4.4 ? Or release binaries for it without official support ?
