### ISSUE TITLE
Syntax error with added library

### ISSUE THREAD

**Issue by Alexlander** [qpython-android/qpython3#9]
Installed Requests with PIP and when I try to run https://github.com/LevPasha/instabot.py/ I get a syntax error somewhere at a line with unicode at python3.2/site-packages/requests/...

**Comment by Alexlander** [comment]
Thought I was on the way to solving it lol. I reinstalled it and now get a slightly different error.

**Comment by riverfor** [comment]
Have you tried the newest QPython3 with Python3.6.1 which is in BETA  ?

https://github.com/qpython-android/qpython3/releases/tag/1.2.0-BETA-2
